export const TelevisionActionTypes = {
    FETCH_TELEVISION_ITEMS_START: 'FETCH_TELEVISION_ITEMS_START',
    FETCH_TELEVISION_ITEMS_SUCCESS: 'FETCH_TELEVISION_ITEMS_SUCCESS',
    FETCH_TELEVISION_ITEMS_FAILURE: 'FETCH_TELEVISION_ITEMS_FAILURE',
}