export const InterviewsActionTypes = {
    FETCH_INTERVIEWS_START: 'FETCH_INTERVIEWS_START',
    FETCH_INTERVIEWS_SUCCESS: 'FETCH_INTERVIEWS_SUCCESS',
    FETCH_INTERVIEWS_FAILURE: 'FETCH_INTERVIEWS_FAILURE',
}