export const ScientificActionTypes = {
  FETCH_SCIENTIFIC_ITEMS_START: "FETCH_SCIENTIFIC_ITEMS_START",
  FETCH_SCIENTIFIC_ITEMS_SUCCESS: "FETCH_SCIENTIFIC_ITEMS_SUCCESS",
  FETCH_SCIENTIFIC_ITEMS_FAILURE: "FETCH_SCIENTIFIC_ITEMS_FAILURE",
}