export const AboutActionTypes = {
    SET_ABOUT_ITEM: 'SET_ABOUT_ITEM',
    FETCH_ABOUTS_START: 'FETCH_ABOUTS_START',
    FETCH_ABOUTS_SUCCESS: 'FETCH_ABOUTS_SUCCESS',
    FETCH_ABOUTS_FAILURE: 'FETCH_ABOUTS_FAILURE',
}